### ISSUE TITLE
Convert HTML/CSS to React.js

### ISSUE THREAD

**Issue by linajin03** [SDSS-UofT/sdss-uoft.github.io#71]

**Comment by yashvk10** [comment]
Hey! I can give assistance in converting the HTMl/CSS to react. I will be happy to help

**Comment by linajin03** [comment]
> Hey! I can give assistance in converting the HTMl/CSS to react. I will be happy to help

Hi! I would love your help. Do you have a different mode of contact?

**Comment by linajin03** [comment]
> Hey! I can give assistance in converting the HTMl/CSS to react. I will be happy to help

Hi! I would love your help. Do you have a different mode of contact?

**Comment by yashvk10** [comment]
yeah, can contact me on slack yashkadam6408@gmail.com
